services:
  - type: web
    name: devalert-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir backend wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5"
      - key: FRONTEND_URL
        value: "https://devalert-backend.onrender.com" # This will be the same as backend URL
      - key: VITE_API_URL
        value: "/api" # Use relative path since they are on same origin
