services:
  - type: web
    name: devalert
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
